### ISSUE TITLE
Problem installing dependecies using Composer

### ISSUE THREAD

**Issue by tugrulcan** [academic/vipa#1765]
### Describe issue
___________________
"hwi/oauth-bundle": "dev-orcid" version not found in [Packagist](https://packagist.org/packages/hwi/oauth-bundle)

### Exception Output
--------------------
`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]

  Invalid configuration for path "hwi_oauth.resource_owners.orcid.type": Unknown resource owner typ
e ""orcid"".`

### Reproduce Step
-----------------
Plase visit [http://labs.play-with-docker.com](http://labs.play-with-docker.com) and create a new session and instance. Run 
`git clone https://github.com/tugrulcan/vipa-dockerised && cd ./vipa-dockerised && git checkout inside_one_container && docker-compose up`

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master"
| Bug?               | no
| New feature?       | no

**Comment by tugrulcan** [comment]
I don't know how but the problem solved by itself. Now I can build the project.
Thank you for consideration.

**Comment by behram** [comment]
travis builds looks stabil. i am closing this issue. if problem occurs again, you can re-open issue everytime ;)
