### ISSUE TITLE
Error while installing Vipa using wizard

### ISSUE THREAD

**Issue by tugrulcan** [academic/vipa#1766]
### Describe issue
___________________
Error occured while proceeding following command: 
`php app/console assetic:dump`

### Exception Output
--------------------
`php app/console assetic:dump --force -n -q

  [RuntimeException]
  Unable to load asset from URL "https://formbuilder.online/assets/css/form-builder.min.css"

assetic:dump [--forks FORKS] [--watch] [--force] [--period PERIOD] [-h|--help] [-q|--quiet] [-v|vv|
vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-is
olation] [-e|--env ENV] [--no-debug] [--] <command> [<write_to>]`

`[2017-05-18 02:17:37] app.ERROR: RuntimeException: Unable to load asset from URL "https://formbuild
er.online/assets/css/form-builder.min.css" (uncaught exception) at /var/www/vipa/vendor/kriswallsmi
th/assetic/src/Assetic/Asset/HttpAsset.php line 61 while running console command `assetic:dump` {"e
xception":"[object] (RuntimeException(code: 0): Unable to load asset from URL \"https://formbuilder
.online/assets/css/form-builder.min.css\" at /var/www/vipa/vendor/kriswallsmith/assetic/src/Assetic
/Asset/HttpAsset.php:61)"}`

### Related Links
-----------------
URL not found "https://formbuilder.online/assets/css/form-builder.min.css"

### Reproduce Step
-----------------

Plase visit [http://labs.play-with-docker.com](http://labs.play-with-docker.com) and create a new session and instance. Run 
`git clone https://github.com/tugrulcan/vipa-dockerised && cd ./vipa-dockerised && git checkout inside_one_container && docker-compose up`

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master"
| Bug?               | no
| New feature?       | no

**Comment by hmert** [comment]
`bower update`

**Comment by tugrulcan** [comment]
@hmert Thanks for answer. I already did, it's still not working.
You can also have a look my Dockerfile instructions here: https://github.com/tugrulcan/vipa_php-fpm/blob/master/Dockerfile#L53

**Comment by behram** [comment]
@tugrulcan you right, i restarted travis and failed with same exception. i will inspect this issue on my freetime. 

related link;
- https://travis-ci.org/academic/vipa/builds/227912003

**Comment by tugrulcan** [comment]
@behram what do you suggest to change for this issue? I have free time and maybe can handle this problem. Just don't have enough experience in PHP.  Can we replace the dependecy with a different one?

**Comment by behram** [comment]
@tugrulcan we using form builder package for workflow bundle, but probably package style files path changed can you replace related style files with existing ones. 

related links;
 - https://github.com/academic/vipa/blob/master/app/config/assetic.yml#L66
 - https://formbuilder.online/

you can resolve this issue, we will be very appreciated.
